### ISSUE TITLE
how can i read localplayer health

### ISSUE THREAD

**Issue by NVR04** [Akandesh/BlazeDumper-Rust#4]
i have this code but idk how to read localplayer and this is not working
`
localPlayer = pm.r_int(proc, game_assembly + offsets.BaseEntity_TypeInfo.offset)
`
`
health = pm.r_int(proc, localPlayer + offsets.BaseCombatEntity._health)
`
returns this
**`
TypeError: Cannot convert python object to uint
`**

**Comment by Akandesh** [comment]
programming issue
