### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by kujoeats** [Akandesh/BlazeDumper-Rust#5]
Can you release the source code you use to detect steam game updates and dump this to github using the bat file that is not public.

Just incase you decide to take it offline. Also release the bat file please and thank you!

Otherwise the offsets for TOD_SKY and CONVAR_ADMIN would be nice to have

**Comment by Akandesh** [comment]
update_rust.bat => `steamcmd\steamcmd.exe +force_install_dir ../rust_client +login username password +app_update 252490 validate +quit`
checkver.bat => `steamcmd\steamcmd.exe +login username password +app_info_update 1 +app_info_print 252490 +quit`
dump.bat => `il2cppdumper\Il2CppDumper.exe "<path to GameAssembly.dll>" "<path to global-metadata.dat>" "<output path>"`

I personally get TOD_SKY through scan_for_klass function which is posted on UC. What do you use CONVAR_ADMIN for if I may ask?

**Comment by kujoeats** [comment]
i use convar_admin to access Time of Day (admin setting), remove water
blur ConVar_Admin_c*
i think it can be used to block admin commands too (such as noclip with
admin flags enabled)
