### ISSUE TITLE
Offsets out of date - new metadata version?

### ISSUE THREAD

**Issue by erobin27** [Akandesh/BlazeDumper-Rust#7]
Hello, I think the offsets are out of date (or I could just be crazy). I tried dumping with il2cpp locally and got an error about metadata version. I think this could be the issue if it is causing the dumper not to work.

```
// Error I get from il2cpp, maybe this helps idk?

Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[29].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 38
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 119
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 94
```

**Comment by Akandesh** [comment]
Yeah you might be correct, looking into it. 

The il2cpp dumper snippet you posted implies that you didn't feed it the correct metadata file. I tried dumping with latest il2cppdumper without any issue.

**Comment by Akandesh** [comment]
Nah the il2cppdumper that's from 2023 is fine, only problem I noticed when updating it was that the script.json file contained unicode variants of < and > so had to fix that. But yeah, now it's updated. 

GLHF, tried updating my stuff but for some reason the camera manager offset inside unityplayer isn't there and it's changed a bit, loaded up with the pdb but I don't remember it being this confusing but there's not much talk about it on uc so probably something obvious I'm missing.

**Comment by erobin27** [comment]
Awesome thank you! I was probably just doing something strange
