### ISSUE TITLE
Missing _

### ISSUE THREAD

**Issue by SandFoxy** [Akandesh/BlazeDumper-Rust#9]
**Missing _**
![image](https://github.com/Akandesh/BlazeDumper-Rust/assets/95248079/e7e24d8f-0faa-4e39-9cfe-822c9a0766f9)

![image](https://github.com/Akandesh/BlazeDumper-Rust/assets/95248079/3b07c95d-a293-4afc-acde-f9323796f0a6)

**Set static_members to true**
bool static_members = false;
![image](https://github.com/Akandesh/BlazeDumper-Rust/assets/95248079/9c79ca3e-9c38-4dcc-b1ff-d9afe096b3e4)

**Comment by SandFoxy** [comment]
also static_ offsets disapeared

**Comment by Akandesh** [comment]
Fixed! Issue wasn't that they defaulted to false, it's that I never passed the bool to the function. 

https://github.com/Akandesh/rust-auto-dumper/commit/885aea7991022c0ae3662908e06c52b53f295409
